### ISSUE TITLE
Add a way to disable all logs

### ISSUE THREAD

**Issue by DumitruCorini** [bonitasoft/bonita-java-client#191]
Currently, all logs are displayed. For example, the createUser() function here : https://github.com/bonitasoft/bonita-java-client/blob/dev/src/main/java/org/bonitasoft/web/client/services/impl/DefaultUserService.java#L73, there is a log.info, so, the user info is displayed by default (with user password being displayed unencrypted). These logs pose a big issue.

**Comment by rbioteau** [comment]
What about configuring the logger ?

**Comment by uguy** [comment]
What about changing the toString method of UserCreateRequest to hide passord (replace with xxx) ?

**Comment by DumitruCorini** [comment]
Changing log level should work, but, this means that on every new install of PM, we need to change it. Also, in PM, the log level can be changed by the user, so, they can change it back anytime and see the passwords of every new user that is created.

Haven't tested to change the toString() method, but does that mean that I need to create a class that herits the UserCreateRequest in our library?

**Comment by uguy** [comment]
I meant contributing to this project since it is open source ;)  (aka PR)

**Comment by DumitruCorini** [comment]
Ok, I'll add a ticket and someone from the R&D will treat it later when working on PM. Thank you for your help
