### ISSUE TITLE
Problem with setting parenthPath for group (create and update)

### ISSUE THREAD

**Issue by thib1111** [bonitasoft/bonita-java-client#254]
Creating and updating groups works for the most part except for the parent path. When i check on the portail the parent path is always empty. I create 2 group, the sfirst is the parent of the second. Bonita refuse to update that field. Here the code i use to update :
GroupUpdateRequest groupUpdateRequest = new GroupUpdateRequest();
groupUpdateRequest.setDescription(group.getDescription());
groupUpdateRequest.setDisplayName(group.getDisplayName());
groupUpdateRequest.setParentPath(group.getParentPath());
groupUpdateRequest.setName(group.getName());

groupAPI.updateGroupById(groupId, groupUpdateRequest);

**Comment by rbioteau** [comment]
Hi, there is indeed an issue with the payload. There should be a `parent_group_id`available to execute the update request properly.

**Comment by rbioteau** [comment]
The 1.0.0 version of the bonita-java-client that contains the fix for this issue has been released
