### ISSUE TITLE
Problem when searching membership for user

### ISSUE THREAD

**Issue by thib1111** [bonitasoft/bonita-java-client#255]
I use this code : 
public static List<Membership> searchForMembership (String userId){
		List<String> listFilter = new ArrayList<String>();
		listFilter.add("f=user_id="+userId);
		List<Membership> resultSearch = membershipAPI.searchMemberships(0, Integer.MAX_VALUE, listFilter, "ROLE_NAME_ASC", "");
		return(resultSearch != null && !resultSearch.isEmpty() ? resultSearch : null); 
	}
And i have this result in the log :
org.bonitasoft.web.rest.server.framework.exception.APIFilterException: Error on filter : Cant search on filter other than user_id

I put the complete error I get in the log.
[MembershipSearchError.txt](https://github.com/bonitasoft/bonita-java-client/files/11331239/MembershipSearchError.txt)

**Comment by rbioteau** [comment]
Hi, 

You can use filters like this:

```java
var result = membershipAPI.searchMemberships(new SearchMembershipsQueryParams()
.p(0)
.c(100)
.f(List.of("user_id=" + userId))
.o("ROLE_NAME_ASC"));
```

**Comment by rbioteau** [comment]
@thib1111 Did it solve your issue ?
