### ISSUE TITLE
Cannot assign human task to user

### ISSUE THREAD

**Issue by tbrielle** [bonitasoft/bonita-java-client#284]
Hi,

Using `HumanTaskApi.updateHumanTaskById(taskId, humanTaskUpdateRequest)` has no effect with Bonita Java Client v1.0.0.

Analysing the request body shows that the following JSON is sent by the client:

```json
{
    "assignedId": "123456789"
}
```
whereas the Bonita User Application sends this JSON:

```json
{
    "assigned_id": "123456789"
}
```

The `HumanTaskUpdateRequest.JSON_PROPERTY_ASSIGNED_ID` value should then be equal to "assigned_id" instead of "assignedId" so that the provided user ID is taken into account.

**Comment by rbioteau** [comment]
Hi, thanks for the report.
In the meantime, you may use the `UserTaskApi` with the `UserTaskUpdateRequest` instead that does not suffer from this inconsistency.

**Comment by rbioteau** [comment]
New api version integrated with https://github.com/bonitasoft/bonita-java-client/commit/ce564816cb54199f8aa7d2067c3b2e11d588a49e
